# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text='Name in english', max_length=50, verbose_name='Name in english')),
                ('name_ru', models.CharField(help_text='Name in russian', max_length=50, verbose_name='Name in russian')),
                ('color', models.CharField(default='#CCCCCC', help_text='HEX number with # like #8f5642', max_length=50, verbose_name='Category  color')),
            ],
            options={
                'verbose_name_plural': 'News categories',
                'verbose_name': 'News category',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, help_text='Title in english', max_length=50, null=True, verbose_name='Title in english')),
                ('content_en', models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Content in english')),
                ('title_ru', models.CharField(blank=True, help_text='Title in russian', max_length=50, null=True, verbose_name='Title in english')),
                ('content_ru', models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Content in russian')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('publish', models.BooleanField(default=True, verbose_name='Published')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='design_app.NewsCategory')),
            ],
            options={
                'verbose_name_plural': 'News items',
                'ordering': ['created'],
                'verbose_name': 'News item',
            },
        ),
    ]
