# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, help_text='Name in english', max_length=140, null=True, verbose_name='Title in english')),
                ('name_ru', models.CharField(blank=True, help_text='Name in russian', max_length=140, null=True, verbose_name='Title in russian')),
            ],
            options={
                'verbose_name': 'Degree',
                'ordering': [],
                'verbose_name_plural': 'Degrees',
            },
        ),
        migrations.CreateModel(
            name='Programm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=4, verbose_name='Number')),
                ('duration', models.IntegerField(default=4, verbose_name='Duration')),
                ('name_en', models.CharField(blank=True, help_text='Name in english', max_length=140, null=True, verbose_name='Name in english')),
                ('content_en', models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Content in english')),
                ('short_en', models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Side in english')),
                ('name_ru', models.CharField(blank=True, help_text='Name in russian', max_length=140, null=True, verbose_name='Name in russian')),
                ('content_ru', models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Content in russian')),
                ('short_ru', models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Side in russian')),
                ('degree', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='design_app.Degree')),
            ],
            options={
                'verbose_name': 'Programm',
                'ordering': [],
                'verbose_name_plural': 'Programmes',
            },
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title_en',
            field=models.CharField(blank=True, help_text='Title in english', max_length=140, null=True, verbose_name='Title in english'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title_ru',
            field=models.CharField(blank=True, help_text='Title in russian', max_length=140, null=True, verbose_name='Title in russian'),
        ),
    ]
