# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0002_auto_20170117_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programm',
            name='short_en',
        ),
        migrations.RemoveField(
            model_name='programm',
            name='short_ru',
        ),
        migrations.AddField(
            model_name='programm',
            name='courses_en',
            field=models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Courses in english'),
        ),
        migrations.AddField(
            model_name='programm',
            name='courses_ru',
            field=models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Courses in russian'),
        ),
        migrations.AddField(
            model_name='programm',
            name='inter_en',
            field=models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='International in english'),
        ),
        migrations.AddField(
            model_name='programm',
            name='inter_ru',
            field=models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='International in russian'),
        ),
        migrations.AddField(
            model_name='programm',
            name='summary_en',
            field=models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Summary in english'),
        ),
        migrations.AddField(
            model_name='programm',
            name='summary_ru',
            field=models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Summary in russian'),
        ),
        migrations.AddField(
            model_name='programm',
            name='tech_en',
            field=models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Tech in english'),
        ),
        migrations.AddField(
            model_name='programm',
            name='tech_ru',
            field=models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Tech in russian'),
        ),
    ]
