# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0003_auto_20170118_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='content_en',
            field=models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Content in english'),
        ),
        migrations.AddField(
            model_name='degree',
            name='content_ru',
            field=models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Content in russian'),
        ),
        migrations.AddField(
            model_name='degree',
            name='pic',
            field=models.ImageField(blank=True, help_text='Title image', null=True, upload_to='degree/titles/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='programm',
            name='color',
            field=models.CharField(default='#CCCCCC', help_text='HEX number with # like #8f5642', max_length=7, verbose_name='Programm  color'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='name_en',
            field=models.CharField(blank=True, help_text='Name in english', max_length=140, null=True, verbose_name='Name in english'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Name in russian', max_length=140, null=True, verbose_name='Name in russian'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='color',
            field=models.CharField(default='#CCCCCC', help_text='HEX number with # like #8f5642', max_length=7, verbose_name='Category  color'),
        ),
    ]
