# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0004_auto_20170118_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programm',
            name='number',
        ),
        migrations.AddField(
            model_name='programm',
            name='form',
            field=models.IntegerField(default=0, verbose_name='Form'),
        ),
    ]
