# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0005_auto_20170118_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programm',
            name='form',
            field=models.IntegerField(choices=[(0, 'intramural'), (1, 'extramural'), (2, 'evening classes')], default=0, verbose_name='Form'),
        ),
    ]
