# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0006_auto_20170118_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programm',
            name='duration',
            field=models.IntegerField(default=4, help_text='in years', verbose_name='Duration'),
        ),
    ]
