# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0007_auto_20170118_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='pos',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='degree',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Show'),
        ),
        migrations.AddField(
            model_name='programm',
            name='pos',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='programm',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Show'),
        ),
    ]
