# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0008_auto_20170118_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degree',
            options={'ordering': ['pos'], 'verbose_name': 'Degree', 'verbose_name_plural': 'Degrees'},
        ),
        migrations.AlterModelOptions(
            name='programm',
            options={'ordering': ['pos'], 'verbose_name': 'Programm', 'verbose_name_plural': 'Programmes'},
        ),
        migrations.AddField(
            model_name='degree',
            name='slug',
            field=models.CharField(default='slug', help_text='it will shows up in address area', max_length=140, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='programm',
            name='slug',
            field=models.CharField(default='slug', help_text='it will shows up in address area', max_length=140, verbose_name='URL'),
        ),
    ]
