# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0011_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=35, verbose_name='Word')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['pos'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AddField(
            model_name='unit',
            name='tag',
            field=models.ManyToManyField(related_name='units', to='design_app.Tag'),
        ),
    ]
