# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 14:32
from __future__ import unicode_literals

import design_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0012_auto_20170118_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='programm',
            name='pic',
            field=models.ImageField(blank=True, help_text='Title image', null=True, upload_to=design_app.models.programm_image_location, verbose_name='image'),
        ),
    ]
