# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:38
from __future__ import unicode_literals

import design_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0013_programm_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, help_text='Title image', null=True, upload_to=design_app.models.image_location, verbose_name='image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
            options={
                'ordering': ['modified'],
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
