# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0014_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='FlatImage',
        ),
        migrations.AlterModelOptions(
            name='flatimage',
            options={'ordering': ['modified'], 'verbose_name': 'Flat image', 'verbose_name_plural': 'Flat images'},
        ),
    ]
