# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 19:33
from __future__ import unicode_literals

import design_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0015_auto_20170119_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=0, verbose_name='Position')),
                ('show', models.BooleanField(default=True, verbose_name='Show')),
                ('name_en', models.CharField(blank=True, help_text='Name in english', max_length=140, null=True, verbose_name='Name in english')),
                ('name_ru', models.CharField(blank=True, help_text='Name in russian', max_length=140, null=True, verbose_name='Name in russian')),
                ('doc', models.FileField(blank=True, help_text='Title image', null=True, upload_to=design_app.models.document_location, verbose_name='image')),
                ('tag', models.ManyToManyField(related_name='documents', to='design_app.Tag')),
            ],
            options={
                'ordering': ['pos'],
                'verbose_name_plural': 'Documents',
                'verbose_name': 'Document',
            },
        ),
    ]
