# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 18:01
from __future__ import unicode_literals

import design_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0016_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=0, verbose_name='Position')),
                ('show', models.BooleanField(default=True, verbose_name='Show')),
                ('pic', models.ImageField(blank=True, help_text='image', null=True, upload_to=design_app.models.programmimage_image_location, verbose_name='image')),
                ('programm', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='design_app.Programm')),
            ],
            options={
                'ordering': ['pos'],
                'verbose_name_plural': 'Programm images',
                'verbose_name': 'Programm image',
            },
        ),
    ]
