# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0017_programmimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmimage',
            name='name_en',
            field=models.CharField(blank=True, help_text='Name in english', max_length=140, null=True, verbose_name='Name in english'),
        ),
        migrations.AddField(
            model_name='programmimage',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Name in russian', max_length=140, null=True, verbose_name='Name in russian'),
        ),
    ]
