# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0018_auto_20170124_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=0, verbose_name='Position')),
                ('show', models.BooleanField(default=True, verbose_name='Show')),
                ('slug', models.CharField(default='slug', help_text='it will shows up in address area', max_length=140, verbose_name='URL')),
                ('name_en', models.CharField(blank=True, help_text='Name in english', max_length=140, null=True, verbose_name='Name in english')),
                ('content_en', models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Content in english')),
                ('name_ru', models.CharField(blank=True, help_text='Name in russian', max_length=140, null=True, verbose_name='Name in russian')),
                ('content_ru', models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Content in russian')),
                ('pic', models.ImageField(blank=True, help_text='Title image', null=True, upload_to='degree/rubrics/', verbose_name='image')),
                ('degree', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='design_app.Degree')),
            ],
            options={
                'ordering': ['pos'],
                'verbose_name_plural': 'Degree rubrics',
                'verbose_name': 'Degree rubric',
            },
        ),
        migrations.AddField(
            model_name='programm',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design_app.Rubric'),
        ),
    ]
