# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:59
from __future__ import unicode_literals

import design_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0019_auto_20170125_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=0, verbose_name='Position')),
                ('show', models.BooleanField(default=True, verbose_name='Show')),
                ('slug', models.CharField(default='slug', help_text='it will shows up in address area', max_length=140, verbose_name='URL')),
                ('name_en', models.CharField(blank=True, help_text='Name in english', max_length=140, null=True, verbose_name='Name in english')),
                ('content_en', models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Content in english')),
                ('name_ru', models.CharField(blank=True, help_text='Name in russian', max_length=140, null=True, verbose_name='Name in russian')),
                ('content_ru', models.TextField(blank=True, help_text='use HTML for better result', null=True, verbose_name='Content in russian')),
                ('cover', models.ImageField(blank=True, help_text='cover image', null=True, upload_to=design_app.models.lab_image_location, verbose_name='image')),
            ],
            options={
                'verbose_name_plural': 'Labs',
                'verbose_name': 'Lab',
                'ordering': ['pos'],
            },
        ),
    ]
