# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 13:34
from __future__ import unicode_literals

import design_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0020_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='pic',
            field=models.ImageField(blank=True, help_text='image', null=True, upload_to=design_app.models.unit_image_location, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='unit',
            name='slug',
            field=models.CharField(default='slug', help_text='it will shows up in address area', max_length=140, verbose_name='URL'),
        ),
    ]
