# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0021_auto_20170425_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='short_en',
            field=models.CharField(blank=True, help_text='Shord desription in english', max_length=140, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='lab',
            name='short_ru',
            field=models.CharField(blank=True, help_text='Shord desription in russian', max_length=140, null=True, verbose_name='description'),
        ),
    ]
