# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0022_auto_20170425_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='cover',
            new_name='pic',
        ),
    ]
