# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0023_auto_20170425_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='featured',
            field=models.BooleanField(default=True, verbose_name='Carousel'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='short_en',
            field=models.CharField(blank=True, help_text='News item preview in english', max_length=140, null=True, verbose_name='Short in english'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='short_ru',
            field=models.CharField(blank=True, help_text='Shord desription in russian', max_length=140, null=True, verbose_name='Short in russian'),
        ),
    ]
