# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 10:06
from __future__ import unicode_literals

import design_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0024_auto_20170426_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='pic',
            field=models.ImageField(blank=True, help_text='Title image', null=True, upload_to=design_app.models.newsitem_image_location, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Carousel'),
        ),
    ]
